/*
 * Copyright 2025 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.ui.specs

import org.openqa.selenium.By
import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.verbs.ShouldVerb
import org.scalatest.{BeforeAndAfterAll, BeforeAndAfterEach, GivenWhenThen}
import uk.gov.hmrc.selenium.webdriver.{Browser, ScreenshotOnFailure}
import uk.gov.hmrc.ui.pages.*
import uk.gov.hmrc.ui.pages.Land.*
import uk.gov.hmrc.ui.pages.Vendor.WhoIsTheVendor
import uk.gov.hmrc.ui.tags.*
import uk.gov.hmrc.ui.util.Users.LoginTypes.HASDIRECT
import uk.gov.hmrc.ui.util.Users.UserTypes.Organisation

class LandQuestionsSpec
    extends AnyFeatureSpec
    with BaseSpec
    with GivenWhenThen
    with ShouldVerb
    with BeforeAndAfterAll
    with BeforeAndAfterEach
    with Browser
    with ScreenshotOnFailure {

  Feature("SDLT Filing Frontend About The Land Questions") {

    Scenario(
      "Complete the Land Questions user journey address lookup used, unregistered with Land Registry, no UPRN (Title and UPRN skipped)",
      wip
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("firstJson"))
      When("the user clicks on the 'Land Questions' link")
      LandBeforeYouStart.clickLinkById("task-list-link-land-questions")
      Then("the user should be navigated to the Land Before you start page page")
      LandBeforeYouStart.verifyPageTitle(LandBeforeYouStart.pageTitle)
      And("clicks the Continue button")
      LandBeforeYouStart.saveAndContinue()
      Then("the user should be navigated to What is the type of property")
      TypeOfProperty.verifyPageTitle(TypeOfProperty.pageTitle)
      And("the user selects the 'Additional Residental Property' radio button")
      TypeOfProperty.radioButton(TypeOfProperty.additional_residential)
      And("clicks the Save and continue button")
      TypeOfProperty.saveAndContinue()
      Then("the user is be navigated to Interest transferred or created page")
      InterestTransferredCreated.verifyPageTitle(InterestTransferredCreated.pageTitle)
      And("the user selects the 'Long Leasehold' radio button and continues")
      InterestTransferredCreated.radioButton(InterestTransferredCreated.LG)
      And("clicks the Save and continue button")
      InterestTransferredCreated.saveAndContinue()
      Then("the user is navigated to the Land Confirm Address page")
      LandConfirmAddress.verifyPageTitle(LandConfirmAddress.pageTitle)
      When("the user selects the 'No' radio button")
      LandConfirmAddress.radioButton(LandConfirmAddress.no)
      And("clicks on Save and Continue button")
      LandConfirmAddress.saveAndContinue()
      Then("the user is navigated to the Land Address page")
      LandAddress.verifyPageTitle(LandAddress.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      LandAddress.clickAddressManually()
      And("enters their address manually")
      LandAddress.verifyPageTitle(LandAddress.editPageTitle)
      LandAddress.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Land Address page to 'Review and confirm the address'")
      LandAddress.verifyPageTitle(LandAddress.confirmPageTitle)
      When("the user clicks the Confirm address button")
      LandAddress.clickContinueButton()
      Then("the user is on What is the local authority code")
      LocalAuthorityCode.verifyPageTitle(LocalAuthorityCode.pageTitle)
      And("the user enters a valid local authority code")
      LocalAuthorityCode.input(
        By.id(LocalAuthorityCode.localAuthCode),
        LocalAuthorityCode.localAuthCodeInput
      )
      And("the user clicks on Save & Continue")
      LocalAuthorityCode.saveAndContinue()
      Then("the user is on Is the land or property registered  with HM Land Registry ?")
      HM_LandRegistration.verifyPageTitle(HM_LandRegistration.pageTitle)
      When("the user selects No and continues")
      HM_LandRegistration.radioButton(HM_LandRegistration.no)
      And("clicks the Save and continue button")
      HM_LandRegistration.saveAndContinue()
      Then("the user is on Do you have an NLPG UPRN for the land or property ?")
      DoYouHaveNLPG.verifyPageTitle(DoYouHaveNLPG.pageTitle)
      And("selects 'No' for having NLPG UPRN")
      DoYouHaveNLPG.radioButton(DoYouHaveNLPG.no)
      And("clicks the Save and continue button")
      DoYouHaveNLPG.saveAndContinue()
      Then("the user is navigated to the Sending Plan By Post page")
      LandSendingPlanByPost.verifyPageTitle(LandSendingPlanByPost.pageTitle)
      When("the user selects the 'Yes' radio button")
      LandSendingPlanByPost.radioButton(LandSendingPlanByPost.yes)
      And("clicks the Save and continue button")
      LandSendingPlanByPost.saveAndContinue()
      Then("the user is navigated to the Land Minerals Or Mineral Rights page")
      LandMineralsOrMineralRights.verifyPageTitle(LandMineralsOrMineralRights.pageTitle)
      When("the user selects the 'No' radio button")
      LandMineralsOrMineralRights.radioButton(LandMineralsOrMineralRights.no)
      And("clicks the Save and continue button")
      LandMineralsOrMineralRights.saveAndContinue()
      Then("the user is on Check your answers page")
      LandCheckYourAnswers.verifyPageTitle(LandCheckYourAnswers.pageTitle)
      When("the user clicks the 'Change' link for type of property")
      LandCheckYourAnswers.clickTypeOfPropertyChange()
      Then("the user should be navigated to What is the type of property")
      TypeOfProperty.verifyPageTitle(TypeOfProperty.pageTitle)
      And("the user selects the 'Residential' radio button")
      TypeOfProperty.radioButton(TypeOfProperty.residential)
      And("clicks the Save and continue button")
      TypeOfProperty.saveAndContinue()
      Then("the user is on Check your answers page")
      LandCheckYourAnswers.verifyPageTitle(LandCheckYourAnswers.pageTitle)
      When("the user clicks the 'Change' link for Interest transferred or created")
      LandCheckYourAnswers.clickInterestTransferredOrCreated()
      Then("the user should be navigated to Interest transferred or created page")
      InterestTransferredCreated.verifyPageTitle(InterestTransferredCreated.pageTitle)
      And("the user selects the 'Other' radio button and continues")
      InterestTransferredCreated.radioButton(InterestTransferredCreated.OT)
      And("clicks the Save and continue button")
      InterestTransferredCreated.saveAndContinue()
      Then("the user is on Check your answers page")
      LandCheckYourAnswers.verifyPageTitle(LandCheckYourAnswers.pageTitle)
      When("the user clicks the 'Change' link for Local Authority Code")
      LandCheckYourAnswers.clickLocalAuthorityCode()
      Then("the user should be navigated to What is the local authority code")
      LocalAuthorityCode.verifyPageTitle(LocalAuthorityCode.pageTitle)
      And("the user enters a different valid local authority code")
      LocalAuthorityCode.input(
        By.id(LocalAuthorityCode.localAuthCode),
        LocalAuthorityCode.welshLocalAuthCodeInput
      )
      And("the user clicks on Save & Continue")
      LocalAuthorityCode.saveAndContinue()
      Then("the user is on Check your answers page")
      LandCheckYourAnswers.verifyPageTitle(LandCheckYourAnswers.pageTitle)
      When("the user clicks the 'Change' link for Is the land or property registered  with HM Land Registry ?")
      LandCheckYourAnswers.clickHMLandRegistration()
      Then("the user should be navigated to Is the land or property registered  with HM Land Registry ? page")
      HM_LandRegistration.verifyPageTitle(HM_LandRegistration.pageTitle)
      When("the user selects Yes and continues")
      HM_LandRegistration.radioButton(HM_LandRegistration.yes)
      And("clicks the Save and continue button")
      HM_LandRegistration.saveAndContinue()
      Then("the user is on Check your answers page")
      LandCheckYourAnswers.verifyPageTitle(LandCheckYourAnswers.pageTitle)
      When("the user clicks the 'Change' link for title number")
      LandCheckYourAnswers.clickTitleNumber()
      Then("the user should be navigated to Land Title number page")
      LandTitleNumber.verifyPageTitle(LandTitleNumber.pageTitle)
      And("The user enters Land Title Number")
      LandTitleNumber.input(By.id(LandTitleNumber.landTitleNumber), LandTitleNumber.landTitleNumberInput)
      Then("the user clicks the Save and continue button")
      LandTitleNumber.saveAndContinue()
      Then("the user is on Check your answers page")
      LandCheckYourAnswers.verifyPageTitle(LandCheckYourAnswers.pageTitle)
      When("the user clicks the 'Change' link for address")
      LandCheckYourAnswers.clickLandAddress()
      Then("the user is navigated to the Land Address page")
      LandAddress.verifyPageTitle(LandAddress.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      LandAddress.clickAddressManually()
      And("enters their address manually")
      LandAddress.verifyPageTitle(LandAddress.editPageTitle)
      LandAddress.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Land Address page to 'Review and confirm the address'")
      LandAddress.verifyPageTitle(LandAddress.confirmPageTitle)
      When("the user clicks the Confirm address button")
      LandAddress.clickContinueButton()
      Then("the user is on Check your answers page")
      LandCheckYourAnswers.verifyPageTitle(LandCheckYourAnswers.pageTitle)
      When("the user selects Save and continue")
      LandCheckYourAnswers.saveAndContinue()
      Then("the user is navigated to the Land Overview page")
      LandOverview.verifyPageTitle(LandOverview.pageTitle)
      When("the user selects the 'Yes' radio button")
      LandOverview.radioButton(LandOverview.yes)
      And("clicks the Continue button")
      LandOverview.saveAndContinue()
    }

    Scenario(
      "Complete the Land Questions user journey with Mixed property with mineral rights routes to agricultural land question and exits without land details",
      LandJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("firstJson"))
      When("the user clicks on the 'Land Questions' link")
      LandBeforeYouStart.clickLinkById("task-list-link-land-questions")
      Then("the user should be navigated to the Land Before you start page page")
      LandBeforeYouStart.verifyPageTitle(LandBeforeYouStart.pageTitle)
      And("clicks the Continue button")
      LandBeforeYouStart.saveAndContinue()
      Then("the user should be navigated to What is the type of property")
      TypeOfProperty.verifyPageTitle(TypeOfProperty.pageTitle)
      And("the user selects the 'Mixed' radio button")
      TypeOfProperty.radioButton(TypeOfProperty.mixed)
      And("clicks the Save and continue button")
      TypeOfProperty.saveAndContinue()
      Then("the user is be navigated to Interest transferred or created page")
      InterestTransferredCreated.verifyPageTitle(InterestTransferredCreated.pageTitle)
      And("the user selects the 'Leasehold subject' radio button and continues")
      InterestTransferredCreated.radioButton(InterestTransferredCreated.LT)
      And("clicks the Save and continue button")
      InterestTransferredCreated.saveAndContinue()
      Then("the user is navigated to the Land Confirm Address page")
      LandConfirmAddress.verifyPageTitle(LandConfirmAddress.pageTitle)
      When("the user selects the 'No' radio button")
      LandConfirmAddress.radioButton(LandConfirmAddress.no)
      And("clicks on Save and Continue button")
      LandConfirmAddress.saveAndContinue()
      Then("the user is navigated to the Land Address page")
      LandAddress.verifyPageTitle(LandAddress.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      LandAddress.clickAddressManually()
      And("enters their address manually")
      LandAddress.verifyPageTitle(LandAddress.editPageTitle)
      LandAddress.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Land Address page to 'Review and confirm the address'")
      LandAddress.verifyPageTitle(LandAddress.confirmPageTitle)
      When("the user clicks the Confirm address button")
      LandAddress.clickContinueButton()
      Then("the user is on What is the local authority code")
      LocalAuthorityCode.verifyPageTitle(LocalAuthorityCode.pageTitle)
      And("the user enters a valid local authority code")
      LocalAuthorityCode.input(
        By.id(LocalAuthorityCode.localAuthCode),
        LocalAuthorityCode.localAuthCodeInput
      )
      And("the user clicks on Save & Continue")
      LocalAuthorityCode.saveAndContinue()
      Then("the user is on Is the land or property registered  with HM Land Registry ?")
      HM_LandRegistration.verifyPageTitle(HM_LandRegistration.pageTitle)
      When("the user selects Yes and continues")
      HM_LandRegistration.radioButton(HM_LandRegistration.yes)
      And("clicks the Save and continue button")
      HM_LandRegistration.saveAndContinue()
      Then("The user is navigated to the Land Title Number Page")
      LandTitleNumber.verifyPageTitle(LandTitleNumber.pageTitle)
      When("The user enters Land Title Number")
      LandTitleNumber.input(By.id(LandTitleNumber.landTitleNumber), LandTitleNumber.landTitleNumberInput)
      And("clicks the Save and continue button")
      LandTitleNumber.saveAndContinue()
      Then("user is on Do you have an NLPG UPRN for the land or property ? page")
      DoYouHaveNLPG.verifyPageTitle(DoYouHaveNLPG.pageTitle)
      And("selects 'No' for having NLPG UPRN")
      DoYouHaveNLPG.radioButton(DoYouHaveNLPG.no)
      And("user clicks Save & Continue")
      DoYouHaveNLPG.saveAndContinue()
      Then("the user is navigated to the Sending Plan By Post page")
      LandSendingPlanByPost.verifyPageTitle(LandSendingPlanByPost.pageTitle)
      When("the user selects the 'No' radio button")
      LandSendingPlanByPost.radioButton(LandSendingPlanByPost.no)
      And("clicks the Save and continue button")
      LandSendingPlanByPost.saveAndContinue()
      Then("the user is navigated to the Land Minerals Or Mineral Rights page")
      LandMineralsOrMineralRights.verifyPageTitle(LandMineralsOrMineralRights.pageTitle)
      When("the user selects the 'Yes' radio button")
      LandMineralsOrMineralRights.radioButton(LandMineralsOrMineralRights.yes)
      And("clicks the Save and continue button")
      LandMineralsOrMineralRights.saveAndContinue()
      Then("the user is navigated to Agricultural Or Developmental Land Page")
      AgriculturalOrDevelopmentalLand.verifyPageTitle(AgriculturalOrDevelopmentalLand.pageTitle)
      When("the user selects the 'No' radio button")
      AgriculturalOrDevelopmentalLand.radioButton(AgriculturalOrDevelopmentalLand.no)
      //      And("clicks the Save and continue button")
      //      AgriculturalOrDevelopmentalLand.saveAndContinue()
      // Then the user is on Check your answers
      // When the user selects Save and continue

      Then("the user is navigated to the Land Overview page")
      LandOverview.navigateToPage(
        "http://localhost:10910/stamp-duty-land-tax-filing/about-the-land/land-or-property-overview"
      )
      LandOverview.verifyPageTitle(LandOverview.pageTitle)
      When("the user selects the 'Yes' radio button")
      LandOverview.radioButton(LandOverview.yes)
      And("clicks the Continue button")
      LandOverview.saveAndContinue()
    }

    Scenario(
      "Complete the Land Questions user journey for  Non residential property with mineral rights and agricultural land without land area details",
      LandJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("firstJson"))
      When("the user clicks on the 'Land Questions' link")
      LandBeforeYouStart.clickLinkById("task-list-link-land-questions")
      Then("the user should be navigated to the Land Before you start page page")
      LandBeforeYouStart.verifyPageTitle(LandBeforeYouStart.pageTitle)
      And("clicks the Continue button")
      LandBeforeYouStart.saveAndContinue()
      Then("the user should be navigated to What is the type of property")
      TypeOfProperty.verifyPageTitle(TypeOfProperty.pageTitle)
      And("the user selects the 'Non-Residential' radio button")
      TypeOfProperty.radioButton(TypeOfProperty.non_residential)
      And("clicks the Save and continue button")
      TypeOfProperty.saveAndContinue()
      Then("the user is be navigated to Interest transferred or created page")
      InterestTransferredCreated.verifyPageTitle(InterestTransferredCreated.pageTitle)
      And("the user selects the 'Other' radio button and continues")
      InterestTransferredCreated.radioButton(InterestTransferredCreated.OT)
      Then("the user clicks the Save and continue button")
      InterestTransferredCreated.saveAndContinue()
      Then("the user is navigated to the Land Confirm Address page")
      LandConfirmAddress.verifyPageTitle(LandConfirmAddress.pageTitle)
      When("the user selects the 'No' radio button")
      LandConfirmAddress.radioButton(LandConfirmAddress.no)
      And("clicks on Save and Continue button")
      LandConfirmAddress.saveAndContinue()
      Then("the user is navigated to the Land Address page")
      LandAddress.verifyPageTitle(LandAddress.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      LandAddress.clickAddressManually()
      And("enters their address manually")
      LandAddress.verifyPageTitle(LandAddress.editPageTitle)
      LandAddress.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Land Address page to 'Review and confirm the address'")
      LandAddress.verifyPageTitle(LandAddress.confirmPageTitle)
      When("the user clicks the Confirm address button")
      LandAddress.clickContinueButton()
      Then("the user is on What is the local authority code")
      LocalAuthorityCode.verifyPageTitle(LocalAuthorityCode.pageTitle)
      And("the user enters a valid local authority code")
      LocalAuthorityCode.input(
        By.id(LocalAuthorityCode.localAuthCode),
        LocalAuthorityCode.localAuthCodeInput
      )
      And("the user clicks on Save & Continue")
      LocalAuthorityCode.saveAndContinue()
      Then("the user is on Is the land or property registered  with HM Land Registry ?")
      HM_LandRegistration.verifyPageTitle(HM_LandRegistration.pageTitle)
      When("the user selects Yes and continues")
      HM_LandRegistration.radioButton(HM_LandRegistration.yes)
      And("clicks the Save and continue button")
      HM_LandRegistration.saveAndContinue()
      Then("The user is navigated to the Land Title Number Page")
      LandTitleNumber.verifyPageTitle(LandTitleNumber.pageTitle)
      When("The user enters Land Title Number")
      LandTitleNumber.input(By.id(LandTitleNumber.landTitleNumber), LandTitleNumber.landTitleNumberInput)
      And("The user selects save and continue")
      LandTitleNumber.saveAndContinue()
      When("user is on Do you have an NLPG UPRN for the land or property ? page")
      DoYouHaveNLPG.verifyPageTitle(DoYouHaveNLPG.pageTitle)
      And("selects 'Yes' for having NLPG UPRN")
      DoYouHaveNLPG.radioButton(DoYouHaveNLPG.yes)
      And("clicks the Save and continue button")
      DoYouHaveNLPG.saveAndContinue()
      Then("the user is on What is the NLPG UPRN for the land or property page")
      NLPGUPRN.verifyPageTitle(NLPGUPRN.pageTitle)
      When("the user enters a valid NLPG UPRN ")
      NLPGUPRN.input(By.id(NLPGUPRN.nlpg_uprn), NLPGUPRN.nlpg_uprnInput)
      And("clicks the Save and continue button")
      NLPGUPRN.saveAndContinue()
      Then("the user is navigated to the Sending Plan By Post page")
      LandSendingPlanByPost.verifyPageTitle(LandSendingPlanByPost.pageTitle)
      When("the user selects the 'No' radio button")
      LandSendingPlanByPost.radioButton(LandSendingPlanByPost.no)
      And("clicks the Save and continue button")
      LandSendingPlanByPost.saveAndContinue()
      Then("the user is navigated to the Land Minerals Or Mineral Rights page")
      LandMineralsOrMineralRights.verifyPageTitle(LandMineralsOrMineralRights.pageTitle)
      When("the user selects the 'Yes' radio button")
      LandMineralsOrMineralRights.radioButton(LandMineralsOrMineralRights.yes)
      And("clicks the Save and continue button")
      LandMineralsOrMineralRights.saveAndContinue()
      Then("the user is navigated to Agricultural Or Developmental Land Page")
      AgriculturalOrDevelopmentalLand.verifyPageTitle(AgriculturalOrDevelopmentalLand.pageTitle)
      When("the user selects the 'Yes' radio button")
      AgriculturalOrDevelopmentalLand.radioButton(AgriculturalOrDevelopmentalLand.yes)
      And("clicks the Save and continue button")
      AgriculturalOrDevelopmentalLand.saveAndContinue()
      Then("the user is navigated to Do you know the area of the land Page")
      AddAreaOfTheLand.verifyPageTitle(AddAreaOfTheLand.pageTitle)
      When("the user select 'no' on the page")
      AddAreaOfTheLand.radioButton(AddAreaOfTheLand.no)
      And("click Save and Continue")
      AddAreaOfTheLand.saveAndContinue()
      // Then("the user navigated to CYA page")
    }

    Scenario(
      "Complete the Land Questions user journey for  Non residential property with minerals, agricultural area in square meters",
      LandJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("firstJson"))
      When("the user clicks on the 'Land Questions' link")
      LandBeforeYouStart.clickLinkById("task-list-link-land-questions")
      Then("the user should be navigated to the Land Before you start page page")
      LandBeforeYouStart.verifyPageTitle(LandBeforeYouStart.pageTitle)
      And("clicks the Continue button")
      LandBeforeYouStart.saveAndContinue()
      Then("the user should be navigated to What is the type of property")
      TypeOfProperty.verifyPageTitle(TypeOfProperty.pageTitle)
      And("the user selects the 'Non-Residential' radio button")
      TypeOfProperty.radioButton(TypeOfProperty.non_residential)
      And("clicks the Save and continue button")
      TypeOfProperty.saveAndContinue()
      Then("the user is be navigated to Interest transferred or created page")
      InterestTransferredCreated.verifyPageTitle(InterestTransferredCreated.pageTitle)
      And("the user selects the 'Freehold vacant position' radio button and continues")
      InterestTransferredCreated.radioButton(InterestTransferredCreated.FP)
      And("clicks the Save and continue button")
      InterestTransferredCreated.saveAndContinue()
      Then("the user is navigated to the Land Confirm Address page")
      LandConfirmAddress.verifyPageTitle(LandConfirmAddress.pageTitle)
      When("the user selects the 'No' radio button")
      LandConfirmAddress.radioButton(LandConfirmAddress.no)
      And("clicks on Save and Continue button")
      LandConfirmAddress.saveAndContinue()
      Then("the user is navigated to the Land Address page")
      LandAddress.verifyPageTitle(LandAddress.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      LandAddress.clickAddressManually()
      And("enters their address manually")
      LandAddress.verifyPageTitle(LandAddress.editPageTitle)
      LandAddress.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Land Address page to 'Review and confirm the address'")
      LandAddress.verifyPageTitle(LandAddress.confirmPageTitle)
      When("the user clicks the Confirm address button")
      LandAddress.clickContinueButton()
      Then("the user is on What is the local authority code")
      LocalAuthorityCode.verifyPageTitle(LocalAuthorityCode.pageTitle)
      And("the user enters a valid local authority code")
      LocalAuthorityCode.input(
        By.id(LocalAuthorityCode.localAuthCode),
        LocalAuthorityCode.localAuthCodeInput
      )
      And("the user clicks on Save & Continue")
      LocalAuthorityCode.saveAndContinue()
      Then("the user is on Is the land or property registered  with HM Land Registry ?")
      HM_LandRegistration.verifyPageTitle(HM_LandRegistration.pageTitle)
      When("the user selects Yes and continues")
      HM_LandRegistration.radioButton(HM_LandRegistration.yes)
      And("clicks the Save and continue button")
      HM_LandRegistration.saveAndContinue()
      Then("The user is navigated to the Land Title Number Page")
      LandTitleNumber.verifyPageTitle(LandTitleNumber.pageTitle)
      When("The user enters Land Title Number")
      LandTitleNumber.input(By.id(LandTitleNumber.landTitleNumber), LandTitleNumber.landTitleNumberInput)
      And("The user selects save and continue")
      LandTitleNumber.saveAndContinue()
      Then("the user is on Do you have an NLPG UPRN for the land or property ?")
      DoYouHaveNLPG.verifyPageTitle(DoYouHaveNLPG.pageTitle)
      And("selects 'No' for having NLPG UPRN")
      DoYouHaveNLPG.radioButton(DoYouHaveNLPG.no)
      And("clicks the Save and continue button")
      DoYouHaveNLPG.saveAndContinue()
      Then("the user is navigated to the Sending Plan By Post page")
      LandSendingPlanByPost.verifyPageTitle(LandSendingPlanByPost.pageTitle)
      When("the user selects the 'Yes' radio button")
      LandSendingPlanByPost.radioButton(LandSendingPlanByPost.yes)
      And("clicks the Save and continue button")
      LandSendingPlanByPost.saveAndContinue()
      Then("the user is navigated to the Land Minerals Or Mineral Rights page")
      LandMineralsOrMineralRights.verifyPageTitle(LandMineralsOrMineralRights.pageTitle)
      When("the user selects the 'Yes' radio button")
      LandMineralsOrMineralRights.radioButton(LandMineralsOrMineralRights.yes)
      And("clicks the Save and continue button")
      LandMineralsOrMineralRights.saveAndContinue()
      Then("the user is navigated to Agricultural Or Developmental Land Page")
      AgriculturalOrDevelopmentalLand.verifyPageTitle(AgriculturalOrDevelopmentalLand.pageTitle)
      When("the user selects the 'Yes' radio button")
      AgriculturalOrDevelopmentalLand.radioButton(AgriculturalOrDevelopmentalLand.yes)
      And("clicks the Save and continue button")
      AgriculturalOrDevelopmentalLand.saveAndContinue()
      Then("the user is navigated to Do you know the area of the land Page")
      AddAreaOfTheLand.verifyPageTitle(AddAreaOfTheLand.pageTitle)
      When("the user select 'yes' on the page")
      AddAreaOfTheLand.radioButton(AddAreaOfTheLand.yes)
      And("click Save and Continue")
      AddAreaOfTheLand.saveAndContinue()
      Then("User is navigated to Select one unit of measurement for the area of land Page")
      UnitOfMeasurement.verifyPageTitle(UnitOfMeasurement.pageTitle)
      When("the user selects 'square metres' as unit of measurement")
      UnitOfMeasurement.radioButton(UnitOfMeasurement.squareMetres)
      And("The user selects save and continue")
      UnitOfMeasurement.saveAndContinue()
      Then("User is navigated to area of the land in square metres page")
      AreaOfTheLand.verifyPageTitle(AreaOfTheLand.pageTitle)
      AreaOfTheLand.verifyElementIsDisplayed(AreaOfTheLand.headerSquareMetre)
      And("The user click on Back link and navigates you back to Unit of measurement page")
      AreaOfTheLand.clickBackLink()
      UnitOfMeasurement.verifyPageTitle(UnitOfMeasurement.pageTitle)
      And("selects 'hectares' as unit of measurement")
      UnitOfMeasurement.radioButton(UnitOfMeasurement.hectares)
      And("The user selects save and continue")
      UnitOfMeasurement.saveAndContinue()
      Then("User is navigated to area of the land in hectares page")
      AreaOfTheLand.verifyPageTitle(AreaOfTheLand.pageTitle)
      AreaOfTheLand.verifyElementIsDisplayed(AreaOfTheLand.headerHectares)
      And(" user enters area in hectares")
      AreaOfTheLand.input(By.id(AreaOfTheLand.area), AreaOfTheLand.areaHectares)
      And("The user selects save and continue")
      AreaOfTheLand.saveAndContinue()
      // Then("the user navigated to CYA page")
    }
    Scenario(
      "Complete the Land Questions user journey Address confirmed, registered with Land Registry, UPRN available (Title and UPRN captured)",
      LandJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("firstJson"))
      When("the user clicks on the 'Land Questions' link")
      LandBeforeYouStart.clickLinkById("task-list-link-land-questions")
      Then("the user should be navigated to the Land Before you start page page")
      LandBeforeYouStart.verifyPageTitle(LandBeforeYouStart.pageTitle)
      And("clicks the Continue button")
      LandBeforeYouStart.saveAndContinue()
      Then("the user should be navigated to What is the type of property")
      TypeOfProperty.verifyPageTitle(TypeOfProperty.pageTitle)
      When("the user selects the 'Residential' radio button")
      TypeOfProperty.radioButton(TypeOfProperty.residential)
      And("clicks the Save and continue button")
      TypeOfProperty.saveAndContinue()
      Then("the user is be navigated to Interest transferred or created page")
      InterestTransferredCreated.verifyPageTitle(InterestTransferredCreated.pageTitle)
      And("the user selects the 'Freehold' radio button and continues")
      InterestTransferredCreated.radioButton(InterestTransferredCreated.FG)
      Then(" the user clicks the Save and continue button")
      InterestTransferredCreated.saveAndContinue()
      Then("the user is navigated to the Land Confirm Address page")
      LandConfirmAddress.verifyPageTitle(LandConfirmAddress.pageTitle)
      When("the user selects the 'No' radio button")
      LandConfirmAddress.radioButton(LandConfirmAddress.no)
      And("clicks on Save and Continue button")
      LandConfirmAddress.saveAndContinue()
      Then("the user is navigated to the Land Address page")
      LandAddress.verifyPageTitle(LandAddress.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      LandAddress.clickAddressManually()
      And("enters their address manually")
      LandAddress.verifyPageTitle(LandAddress.editPageTitle)
      LandAddress.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Land Address page to 'Review and confirm the address'")
      LandAddress.verifyPageTitle(LandAddress.confirmPageTitle)
      When("the user clicks the Confirm address button")
      LandAddress.clickContinueButton()
      Then("the user is on What is the local authority code")
      LocalAuthorityCode.verifyPageTitle(LocalAuthorityCode.pageTitle)
      And("the user enters a valid local authority code")
      LocalAuthorityCode.input(
        By.id(LocalAuthorityCode.localAuthCode),
        LocalAuthorityCode.localAuthCodeInput
      )
      And("the user clicks on Save & Continue")
      LocalAuthorityCode.saveAndContinue()
      Then("the user is on Is the land or property registered  with HM Land Registry ?")
      HM_LandRegistration.verifyPageTitle(HM_LandRegistration.pageTitle)
      When("the user selects Yes and continues")
      HM_LandRegistration.radioButton(HM_LandRegistration.yes)
      And("clicks the Save and continue button")
      HM_LandRegistration.saveAndContinue()
      Then("The user is navigated to the Land Title Number Page")
      LandTitleNumber.verifyPageTitle(LandTitleNumber.pageTitle)
      When("The user enters Land Title Number")
      LandTitleNumber.input(By.id(LandTitleNumber.landTitleNumber), LandTitleNumber.landTitleNumberInput)
      And("clicks the Save and continue button")
      LandTitleNumber.saveAndContinue()
      Then("the user is on Do you have an NLPG UPRN for the land or property ?")
      DoYouHaveNLPG.verifyPageTitle(DoYouHaveNLPG.pageTitle)
      And("selects 'Yes' for having NLPG UPRN")
      DoYouHaveNLPG.radioButton(DoYouHaveNLPG.yes)
      And("clicks the Save and continue button")
      DoYouHaveNLPG.saveAndContinue()
      Then("the user is on What is the NLPG UPRN for the land or property page")
      NLPGUPRN.verifyPageTitle(NLPGUPRN.pageTitle)
      When("the user enters a valid NLPG UPRN ")
      NLPGUPRN.input(By.id(NLPGUPRN.nlpg_uprn), NLPGUPRN.nlpg_uprnInput)
      And("clicks the Save and continue button")
      NLPGUPRN.saveAndContinue()
      Then("the user is navigated to the Sending Plan By Post page")
      LandSendingPlanByPost.verifyPageTitle(LandSendingPlanByPost.pageTitle)
      When("the user selects the 'Yes' radio button")
      LandSendingPlanByPost.radioButton(LandSendingPlanByPost.yes)
      And("clicks the Save and continue button")
      LandSendingPlanByPost.saveAndContinue()
      Then("the user is navigated to the Land Minerals Or Mineral Rights page")
      LandMineralsOrMineralRights.verifyPageTitle(LandMineralsOrMineralRights.pageTitle)
      When("the user selects the 'No' radio button")
      LandMineralsOrMineralRights.radioButton(LandMineralsOrMineralRights.no)
      // uncomment next two lines when navigation to the next page is ready
      // And("clicks the Save and continue button")
      // LandMineralsOrMineralRights.saveAndContinue()

      // Then the user is on Check your answers
      // When the user selects Save and continue

      Then("the user is navigated to the Land Overview page")
      LandOverview.navigateToPage(
        "http://localhost:10910/stamp-duty-land-tax-filing/about-the-land/land-or-property-overview"
      )
      LandOverview.verifyPageTitle(LandOverview.pageTitle)
      When("the user selects the 'Yes' radio button")
      LandOverview.radioButton(LandOverview.yes)
      And("clicks the Continue button")
      LandOverview.saveAndContinue()
    }

    Scenario(
      "Validating the overview, update and removing functionality of a Land",
      LandJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(
        HASDIRECT,
        Organisation,
        returnId = Some("full-purchaser-with-agent-land-transaction-uk-authcodes")
      )
      When("the user clicks on the 'Land Questions' link")
      LandBeforeYouStart.clickLinkById("task-list-link-land-questions")
      Then("the user is navigated to the Land Overview page")
      LandOverview.verifyPageTitle(LandOverview.pageTitle)
      When("the user clicks the 'Remove' link to remove land")
      LandOverview.clickLandRemove()
      Then("the user is navigated to remove land page")
      LandRemove.verifyPageTitle(LandRemove.pageTitle)
      When("the user selects no radio button")
      LandRemove.radioButton(LandRemove.no)
      And("clicks Save & Continue")
      LandRemove.saveAndContinue()
      Then("the user is navigated to the Land Overview page")
      LandOverview.verifyPageTitle(LandOverview.pageTitle)
      When("the user clicks the 'Remove' link to remove land")
      LandOverview.clickLandRemove()
      Then("the user is navigated to remove land page")
      LandRemove.verifyPageTitle(LandRemove.pageTitle)
      When("the user selects yes radio button")
      LandRemove.radioButton(LandRemove.yes)
      And("clicks Save & Continue")
      LandRemove.saveAndContinue()
      Then("the user is navigated to the Land Overview page")
      LandOverview.verifyPageTitle(LandOverview.pageTitle)
    }
  }
}
