/*
 * Copyright 2025 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.ui.specs

import org.openqa.selenium.By
import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.verbs.ShouldVerb
import org.scalatest.{BeforeAndAfterAll, BeforeAndAfterEach, GivenWhenThen}
import uk.gov.hmrc.selenium.webdriver.{Browser, ScreenshotOnFailure}
import uk.gov.hmrc.ui.pages.*
import uk.gov.hmrc.ui.pages.Vendor.*
import uk.gov.hmrc.ui.pages.purchaser.*
import uk.gov.hmrc.ui.util.Users.LoginTypes.HASDIRECT
import uk.gov.hmrc.ui.util.Users.UserTypes.Organisation
import uk.gov.hmrc.ui.tags.*

class PurchaserQuestionsSpec
    extends AnyFeatureSpec
    with BaseSpec
    with GivenWhenThen
    with ShouldVerb
    with BeforeAndAfterAll
    with BeforeAndAfterEach
    with Browser
    with ScreenshotOnFailure {

  Feature("SDLT Filing Frontend Purchaser Questions") {
    Scenario(
      "Complete the Main Purchaser Questions user journey as a Individual when there is no purchaser added",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user should be navigated to the Purchaser Before you start page page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      And("clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      /*Then("the user should be navigated to the confirm page when there isn't a full purchaser (no address line 1)")
      PurchaserConfirmNameOfPurchaserPage.verifyPageTitle(PurchaserConfirmNameOfPurchaserPage.pageTitle)
      And("the user clicks yes")
      PurchaserConfirmNameOfPurchaserPage.radioButton(PurchaserConfirmNameOfPurchaserPage.yes)
      PurchaserConfirmNameOfPurchaserPage.saveAndContinue()*/
      Then("the user should be on who is the purchaser page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      And("the user clicks individual")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.individual)
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user should be on the What is the purchaser’s name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      And("the user inputs all fields")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.forename1Id), "forename1")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.forename2Id), "forename2")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.surnameId), "surname")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user should be redirected to address lookup")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user should be navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitle)
      And("clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("User should be navigated to Do you want to add phone number?")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      And("user selects No on the page")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("user clicks Save and Continue")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user lands on to the Does Purchaser have NI page")
      DoesPurchaserHaveNI.verifyPageTitle(DoesPurchaserHaveNI.pageTitle)
      And("user selects Yes on the page")
      DoesPurchaserHaveNI.radioButton(DoesPurchaserHaveNI.yes)
      And("the user click Save and Continue")
      DoesPurchaserHaveNI.saveAndContinue()
      Then("the user navigates to What is Purchaser's National Insurance Page")
      PurchaserNationalinsuranceNumberPage.verifyPageTitle(PurchaserNationalinsuranceNumberPage.pageTitle)
      And("User enter a valid National Insurance Number")
      PurchaserNationalinsuranceNumberPage.input(
        By.id(PurchaserNationalinsuranceNumberPage.Nino),
        PurchaserNationalinsuranceNumberPage.NinoValue
      )
      And("the user click Save and Continue")
      PurchaserNationalinsuranceNumberPage.saveAndContinue()
      Then("User should be navigated to What is purchaser Date of Birth page")
      PurchaserDateOfBirth.verifyPageTitle(PurchaserDateOfBirth.pageTitle)
      And("User enters Purchaser's Date of Birth")
      PurchaserDateOfBirth.enterDateOfBirth()
      And("the user click Save and Continue")
      PurchaserDateOfBirth.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to Are the Purchaser and Vendor Connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      When("User clicks on change link for purchaser name")
      PurchaserCheckYourAnswers.clickPurchaserNameChange()
      Then("User should be navigated to purchaser name page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      And("User updates purchaser name details")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.surnameId), "Updated surname")
      Then("User clicks on save and continue")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on change link for purchaser NI number")
      PurchaserCheckYourAnswers.clickPurchaserNINumberChange()
      And("User should be navigated to purchaser NI number page")
      PurchaserNationalinsuranceNumberPage.verifyPageTitle(PurchaserNationalinsuranceNumberPage.pageTitle)
      And("User updates purchaser NI number details")
      PurchaserNationalinsuranceNumberPage.input(By.id(PurchaserNationalinsuranceNumberPage.Nino), "NJ123456C")
      And("User clicks on save and continue")
      PurchaserNationalinsuranceNumberPage.saveAndContinue()
      Then("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      When("User clicks on change link for purchaser date of birth")
      PurchaserCheckYourAnswers.clickPurchaserDOBChange()
      Then("User should be navigated to purchaser date of birth page")
      PurchaserDateOfBirth.verifyPageTitle(PurchaserDateOfBirth.pageTitle)
      And("User updates purchaser date of birth details")
      PurchaserDateOfBirth.enterDateOfBirth()
      Then("User clicks on save and continue")
      PurchaserDateOfBirth.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on save and continue")
      PurchaserCheckYourAnswers.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Return Tasklist page")

    }

    Scenario(
      "Complete the Main Purchaser Questions user journey as a Individual who doesn't have NI",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user should be navigated to the Purchaser Before you start page page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      And("clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      /* Then("the user should be navigated to the confirm page when there isn't a full purchaser (no address line 1)")
      PurchaserConfirmNameOfPurchaserPage.verifyPageTitle(PurchaserConfirmNameOfPurchaserPage.pageTitle)
      And("the user clicks no")
      PurchaserConfirmNameOfPurchaserPage.radioButton(PurchaserConfirmNameOfPurchaserPage.no)
      PurchaserConfirmNameOfPurchaserPage.saveAndContinue()*/
      Then("the user should be on who is the purchaser page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      And("the user clicks individual")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.individual)
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user should be on the What is the purchaser’s name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      And("the user inputs all fields")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.forename1Id), "forename1")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.forename2Id), "forename2")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.surnameId), "surname")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user should be redirected to address lookup")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user should be navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitle)
      And("clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      // Scenario to cover individual purchaser without NI number
      Then("User should be navigated to Do you want to add phone number?")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      And("user selects Yes on the page")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.yes)
      And("user clicks Save and Continue")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("user navigates to enter phone number for purchaser page")
      PurchaserContactPhoneNumber.verifyPageTitle(PurchaserContactPhoneNumber.pageTitle)
      And("User enters phone number")
      PurchaserContactPhoneNumber.input(
        By.id(PurchaserContactPhoneNumber.phoneNumberInputField),
        PurchaserContactPhoneNumber.phoneNumberValue
      )
      And("user clicks Save and Continue")
      PurchaserContactPhoneNumber.saveAndContinue()
      Then("the user lands on to the Does Purchaser have NI page")
      DoesPurchaserHaveNI.verifyPageTitle(DoesPurchaserHaveNI.pageTitle)
      And("user selects No on the page")
      DoesPurchaserHaveNI.radioButton(DoesPurchaserHaveNI.no)
      And("the user click Save and Continue")
      DoesPurchaserHaveNI.saveAndContinue()
      Then("User should be navigated to Provide a form of ID for purchaser page")
      IndividualPurchaserIDPage.verifyPageTitle(IndividualPurchaserIDPage.pageTitle)
      When("User enters ID details")
      IndividualPurchaserIDPage.input(
        By.id(IndividualPurchaserIDPage.purchaserIdNumberOrReference),
        IndividualPurchaserIDPage.idNumberOrReferenceInput
      )
      And("User enters Country Issued details")
      IndividualPurchaserIDPage.input(
        By.id(IndividualPurchaserIDPage.purchaserCountryIssued),
        IndividualPurchaserIDPage.countryIssuedInput
      )
      And("User clicks Save and Continue")
      IndividualPurchaserIDPage.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'No' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.no)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the Purchaser and Vendor Connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on change link for purchaser address")
      PurchaserCheckYourAnswers.clickPurchaserAddressChange()
      Then("User should be navigated to purchaser address page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitle)
      And("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their updated address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      PurchaserAddressPage.enterAddressManually("123", "TEST", "ZZ11 1ZZ")
      And("User clicks on save and continue")
      PurchaserAddressPage.clickContinueButton()
      Then("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on change link for purchaser phone number")
      PurchaserCheckYourAnswers.clickPurchaserPhoneNumberChange()
      Then("User should be navigated to purchaser phone number page")
      PurchaserContactPhoneNumber.verifyPageTitle(PurchaserContactPhoneNumber.pageTitle)
      And("User updates purchaser phone number details")
      PurchaserContactPhoneNumber.input(
        By.id(PurchaserContactPhoneNumber.phoneNumberInputField),
        "07122256789"
      )
      Then("User clicks on save and continue")
      PurchaserContactPhoneNumber.saveAndContinue()
      Then("User should be navigated to purchasers check your answers page")
      // PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on change link for purchaser ID details")
      PurchaserCheckYourAnswers.clickIndivFormOfIDChange()
      Then("User should be navigated to purchaser ID page")
      IndividualPurchaserIDPage.verifyPageTitle(IndividualPurchaserIDPage.pageTitle)
      And("User updates purchaser ID details")
      IndividualPurchaserIDPage.input(
        By.id(IndividualPurchaserIDPage.purchaserIdNumberOrReference),
        "UPDATEDID22345"
      )
      Then("User clicks on save and continue")
      IndividualPurchaserIDPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on save and continue")
      PurchaserCheckYourAnswers.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Return Tasklist page")
    }

    Scenario(
      "Complete the Main Purchaser Questions user journey as a Individual and later change to company in CYA page",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user should be navigated to the Purchaser Before you start page page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      And("clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      /*Then("the user should be navigated to the confirm page when there isn't a full purchaser (no address line 1)")
      PurchaserConfirmNameOfPurchaserPage.verifyPageTitle(PurchaserConfirmNameOfPurchaserPage.pageTitle)
      And("the user clicks yes")
      PurchaserConfirmNameOfPurchaserPage.radioButton(PurchaserConfirmNameOfPurchaserPage.yes)
      PurchaserConfirmNameOfPurchaserPage.saveAndContinue()*/
      Then("the user should be on who is the purchaser page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      And("the user clicks individual")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.individual)
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user should be on the What is the purchaser’s name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      And("the user inputs all fields")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.forename1Id), "forename1")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.forename2Id), "forename2")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.surnameId), "surname")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user should be redirected to address lookup")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user should be navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitle)
      And("clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("User should be navigated to Do you want to add phone number?")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      And("user selects No on the page")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("user clicks Save and Continue")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user lands on to the Does Purchaser have NI page")
      DoesPurchaserHaveNI.verifyPageTitle(DoesPurchaserHaveNI.pageTitle)
      And("user selects Yes on the page")
      DoesPurchaserHaveNI.radioButton(DoesPurchaserHaveNI.yes)
      And("the user click Save and Continue")
      DoesPurchaserHaveNI.saveAndContinue()
      Then("the user navigates to What is Purchaser's National Insurance Page")
      PurchaserNationalinsuranceNumberPage.verifyPageTitle(PurchaserNationalinsuranceNumberPage.pageTitle)
      And("User enter a valid National Insurance Number")
      PurchaserNationalinsuranceNumberPage.input(
        By.id(PurchaserNationalinsuranceNumberPage.Nino),
        PurchaserNationalinsuranceNumberPage.NinoValue
      )
      And("the user click Save and Continue")
      PurchaserNationalinsuranceNumberPage.saveAndContinue()
      Then("User should be navigated to What is purchaser Date of Birth page")
      PurchaserDateOfBirth.verifyPageTitle(PurchaserDateOfBirth.pageTitle)
      And("User enters Purchaser's Date of Birth")
      PurchaserDateOfBirth.enterDateOfBirth()
      And("the user click Save and Continue")
      PurchaserDateOfBirth.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to Are the Purchaser and Vendor Connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on change link for purchaser type")
      PurchaserCheckYourAnswers.clickPurchaserTypeChange()
      Then("User should be navigated to who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      And("the user clicks company")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.company)
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user should be on the CYA page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on link for missing form ID")
      PurchaserCheckYourAnswers.clickFormOfIDChange()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitle)
      When("the user selects the 'partnership UTR registration number' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.partnershipUTR)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      And("user clicks the Continue button")
      VATRegistrationNumberPage.saveAndContinue()
      Then("User navigates to CYA Page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on link for missing UTR number")
      PurchaserCheckYourAnswers.clickUTRNumberChange()
      Then("the user navigates to  UTR number page")
      PurchaserCorporationTaxUTRPage.verifyPageTitle(PurchaserCorporationTaxUTRPage.pageTitle)
      When("user enters  UTR number")
      PurchaserCorporationTaxUTRPage.input(
        By.id(PurchaserCorporationTaxUTRPage.corporationTaxUTR),
        PurchaserCorporationTaxUTRPage.corporationTaxUTRInput
      )
      And("user clicks the Continue button")
      PurchaserCorporationTaxUTRPage.saveAndContinue()
      Then("User navigates to CYA Page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on save and continue")
      PurchaserCheckYourAnswers.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
    }
    Scenario(
      "Complete the Additional Purchaser Questions user journey as a Individual",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("full-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserOverviewPage.radioButton(PurchaserOverviewPage.yes)
      And("clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user should be navigated to the Purchaser Before you start page page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      And("clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      // User should be navigated to is XXX the surname of the purchaser page
      // User clicks No radio button
      // User clicks Save and Continue
      Then("the user should be on who is the purchaser page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      And("the user clicks individual")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.individual)
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user should be on the What is the purchaser’s name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      And("the user inputs all fields")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.forename1Id), "forename1")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.forename2Id), "forename2")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.surnameId), "surname")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user should be redirected to address lookup")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user should be navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitle)
      And("clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("User should be navigated to Do you want to add phone number?")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      And("user selects Yes on the page")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.yes)
      And("user clicks Save and Continue")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("user navigates to enter phone number for purchaser page")
      PurchaserContactPhoneNumber.verifyPageTitle(PurchaserContactPhoneNumber.pageTitle)
      And("User enters phone number")
      PurchaserContactPhoneNumber.input(
        By.id(PurchaserContactPhoneNumber.phoneNumberInputField),
        PurchaserContactPhoneNumber.phoneNumberValue
      )
      And("user clicks Save and Continue")
      PurchaserContactPhoneNumber.saveAndContinue()
      Then("the user is navigated to the Purchaser check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
    }

    Scenario(
      "Complete the Main Purchaser Questions user journey as a Company with VAT ID",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user should be navigated to the Purchaser Before you start page page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      And("clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      /*Then("the user should be navigated to the confirm page when there isn't a full purchaser (no address line 1)")
      PurchaserConfirmNameOfPurchaserPage.verifyPageTitle(PurchaserConfirmNameOfPurchaserPage.pageTitle)
      And("the user clicks yes")
      PurchaserConfirmNameOfPurchaserPage.radioButton(PurchaserConfirmNameOfPurchaserPage.no)
      PurchaserConfirmNameOfPurchaserPage.saveAndContinue()*/
      Then("the user should be on who is the purchaser page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      And("the user clicks company")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.company)
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user should be on the What is the purchaser’s name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      And("the user inputs company name")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.companyId), "Company Name")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user should be redirected to address lookup")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitleCompany)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompany)
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompany)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user should be navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitleCompany)
      And("clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("User should be navigated to Do you want to add phone number?")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      And("user selects No on the page")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("user clicks Save and Continue")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitle)
      When("the user selects the 'VAT registration number' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.vatRegistrationNumber)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user navigates to VAT Registration number page")
      VATRegistrationNumberPage.verifyPageTitle(VATRegistrationNumberPage.pageTitle)
      And("user enters VAT registration number")
      VATRegistrationNumberPage.input(By.id(VATRegistrationNumberPage.vat), VATRegistrationNumberPage.VATNumber)
      And("user clicks the Continue button")
      VATRegistrationNumberPage.saveAndContinue()
      Then("the user navigates to What type of company page?")
      WhatTypeOfCompany.verifyPageTitle(WhatTypeOfCompany.pageTitle)
      And("user selects 4 types of company")
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Bank, true)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Building_Association, true)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Insurance_Assurance_company, true)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Property_company, true)
      And("user clicks the Continue button")
      WhatTypeOfCompany.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the Purchaser and Vendor Connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on change link for purchaser name")
      PurchaserCheckYourAnswers.clickPurchaserNameChange()
      Then("User should be navigated to purchaser name page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      And("User updates purchaser name details")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.companyId), "Updated Company Name")
      Then("User clicks on save and continue")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on change link for purchaser VAT number")
      PurchaserCheckYourAnswers.clickVATRegistrationNumberChange()
      Then("User should be navigated to purchaser VAT number page")
      VATRegistrationNumberPage.verifyPageTitle(VATRegistrationNumberPage.pageTitle)
      And("User updates purchaser VAT number details")
      VATRegistrationNumberPage.input(By.id(VATRegistrationNumberPage.vat), "069425349")
      Then("User clicks on save and continue")
      VATRegistrationNumberPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on save and continue")
      PurchaserCheckYourAnswers.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Return Tasklist page")

      // User should be navigated to purchaser overview page
      // User selects no to add another purchaser
      // User should be navigated to return tasklist page
    }

    Scenario(
      "Complete the Purchaser Questions user journey as a Company with corporation UTR ID for incomplete purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("incomplete-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserOverviewPage.radioButton(PurchaserOverviewPage.yes)
      And("clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user should be navigated to the Purchaser Before you start page page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      And("clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      Then("the user should be navigated to the confirm page the company name of the purchaser")
      PurchaserConfirmNameOfPurchaserPage.verifyPageTitle(PurchaserConfirmNameOfPurchaserPage.pageTitle)
      And("the user clicks yes")
      PurchaserConfirmNameOfPurchaserPage.radioButton(PurchaserConfirmNameOfPurchaserPage.yes)
      And("clicks Save and Continue")
      PurchaserConfirmNameOfPurchaserPage.saveAndContinue()
      Then("the user should be redirected to address lookup")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitleCompanyStub)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompanyStub)
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompanyStub)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user should be navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitleCompanyStub)
      And("clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("User should be navigated to Do you want to add phone number?")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      And("user selects No on the page")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("user clicks Save and Continue")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitleStub)
      When("the user selects the 'Corporation tax Unique Taxpayer Reference (UTR)' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.corporationTaxUTR)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user is navigated to the Corporation Tax UTR page")
      PurchaserCorporationTaxUTRPage.verifyPageTitle(PurchaserCorporationTaxUTRPage.pageTitle)
      When("the user inputs their company's Corporation tax Unique Taxpayer Reference (UTR)")
      PurchaserCorporationTaxUTRPage.input(
        By.id(PurchaserCorporationTaxUTRPage.corporationTaxUTR),
        PurchaserCorporationTaxUTRPage.corporationTaxUTRInput
      )
      And("clicks the Save and continue button")
      PurchaserCorporationTaxUTRPage.saveAndContinue()
      Then("the user navigates to What type of company page?")
      WhatTypeOfCompany.verifyPageTitle(WhatTypeOfCompany.pageTitle)
      And("user selects 3 types of company")
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Public_corporation, true)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Central_Government, true)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Other_financial_institute, true)
      And("user clicks the Continue button")
      WhatTypeOfCompany.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the Purchaser and Vendor Connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      When("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on change link for purchaser Identity")
      PurchaserCheckYourAnswers.clickFormOfIDChange()
      Then("User should be navigated to purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitleStub)
      And("User updates purchaser Identity details to partnership UTR")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.partnershipUTR)
      Then("User clicks on save and continue")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks link for missing purchaser partnership UTR")
      PurchaserCheckYourAnswers.clickPartnershipUTRNumberChange()
      Then("the user is navigated to the Partnership UTR page")
      PartnershipUTRPage.verifyPageTitle(PartnershipUTRPage.pageTitle)
      And("user enters partnership UTR number")
      PartnershipUTRPage.input(By.id(PartnershipUTRPage.purchaserUTRReference), PartnershipUTRPage.purchaserUTRInput)
      Then("User clicks on save and continue")
      PartnershipUTRPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on save and continue")
      PurchaserCheckYourAnswers.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the 'Change' link for Purchaser")
      PurchaserOverviewPage.clickPurchaserChange()
    }

    Scenario(
      "Complete the Main Purchaser Questions user journey as a Company with partnership UTR ID with no purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user should be navigated to the Purchaser Before you start page page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      And("clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      Then("the user should be on who is the purchaser page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      And("the user clicks company")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.company)
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user should be on the What is the purchaser’s name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      And("the user inputs company name")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.companyId), "Company Name")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user should be redirected to address lookup")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitleCompany)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompany)
      And("enters their address manually")
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user should be navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitleCompany)
      And("clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("User should be navigated to Do you want to add phone number?")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      And("user selects No on the page")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("user clicks Save and Continue")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitle)
      When("the user selects the 'Partnership Unique Taxpayer Reference (UTR)' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.partnershipUTR)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user navigates to the Partnership UTR page")
      PartnershipUTRPage.verifyPageTitle(PartnershipUTRPage.pageTitle)
      And("user enters partnership UTR number")
      PartnershipUTRPage.input(By.id(PartnershipUTRPage.purchaserUTRReference), PartnershipUTRPage.purchaserUTRInput)
      And("clicks the Continue button")
      PartnershipUTRPage.saveAndContinue()
      Then("the user navigates to What type of company page?")
      WhatTypeOfCompany.verifyPageTitle(WhatTypeOfCompany.pageTitle)
      And("user selects 3 types of company")
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Local_authority, true)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Unincorporated_sole_trader_other_than_builder, true)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Superannuation_or_pension_fund, true)
      And("user clicks the Continue button")
      WhatTypeOfCompany.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the Purchaser and Vendor Connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      When("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on change link for does purchaser have phone number")
      PurchaserCheckYourAnswers.clickAddPhoneNumberChange()
      Then("User should be navigated to does purchaser have phone number page")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      And("User updates yes for phone number")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.yes)
      Then("User clicks on save and continue")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on link for missing purchaser phone number")
      PurchaserCheckYourAnswers.clickPurchaserPhoneNumberChange()
      Then("user navigates to enter phone number for purchaser page")
      PurchaserContactPhoneNumber.verifyPageTitle(PurchaserContactPhoneNumber.pageTitle)
      And("User enters phone number")
      PurchaserContactPhoneNumber.input(
        By.id(PurchaserContactPhoneNumber.phoneNumberInputField),
        PurchaserContactPhoneNumber.phoneNumberValue
      )
      And("user clicks Save and Continue")
      PurchaserContactPhoneNumber.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on change link for type of company")
      PurchaserCheckYourAnswers.clickTypeOfCompanyChange()
      Then("User should be navigated to type of company page")
      WhatTypeOfCompany.verifyPageTitle(WhatTypeOfCompany.pageTitle)
      And("User updates type of company details")
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Unincorporated_sole_trader_other_than_builder, false)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Superannuation_or_pension_fund, false)
      Then("User clicks on save and continue")
      WhatTypeOfCompany.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on save and continue")
      PurchaserCheckYourAnswers.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Return Tasklist page")
    }

    Scenario(
      "Complete the Main Purchaser Questions user journey as a Company, providing phone number details along with another form of ID with no purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user should be navigated to the Purchaser Before you start page page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      And("clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      Then("the user should be on who is the purchaser page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      And("the user clicks company")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.company)
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user should be on the What is the purchaser’s name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      And("the user inputs company name")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.companyId), "Company Name")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user should be redirected to address lookup")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitleCompany)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompany)
      And("enters their address manually")
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user should be navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitleCompany)
      And("clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("User should be navigated to Do you want to add phone number?")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      And("user selects Yes on the page")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.yes)
      And("user clicks Save and Continue")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("user navigates to enter phone number for purchaser page")
      PurchaserContactPhoneNumber.verifyPageTitle(PurchaserContactPhoneNumber.pageTitle)
      And("User enters phone number")
      PurchaserContactPhoneNumber.input(
        By.id(PurchaserContactPhoneNumber.phoneNumberInputField),
        PurchaserContactPhoneNumber.phoneNumberValue
      )
      And("user clicks Save and Continue")
      PurchaserContactPhoneNumber.saveAndContinue()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitle)
      When("the user selects the 'Another form of ID' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.anotherFormOfID)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user is navigated to the Form of ID Company page")
      PurchaserFormOfIDCompanyPage.verifyPageTitle(PurchaserFormOfIDCompanyPage.pageTitle)
      When("the user inputs their ID number or reference")
      PurchaserFormOfIDCompanyPage.input(
        By.id(PurchaserFormOfIDCompanyPage.idNumberOrReference),
        PurchaserFormOfIDCompanyPage.idNumberOrReferenceInput
      )
      And("inputs their Country of issue")
      PurchaserFormOfIDCompanyPage.input(
        By.id(PurchaserFormOfIDCompanyPage.countryOfIssue),
        PurchaserFormOfIDCompanyPage.countryOfIssueInput
      )
      And("clicks the Save and continue button")
      PurchaserFormOfIDCompanyPage.saveAndContinue()
      Then("the user navigates to What type of company page?")
      WhatTypeOfCompany.verifyPageTitle(WhatTypeOfCompany.pageTitle)
      And("user selects 3 types of company")
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Unincorporated_builder, true)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Partnership, true)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Insurance_Assurance_company, true)
      And("user clicks the Continue button")
      WhatTypeOfCompany.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the Purchaser and Vendor Connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on change link for purchaser Acting as a Trustee")
      PurchaserCheckYourAnswers.clickIsCompanyActingAsTrusteeChange()
      Then("User should be navigated to purchaser Acting as a Trustee page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      And("User updates purchaser Acting as a Trustee details to No")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.no)
      Then("User clicks on save and continue")
      PurchaserActingAsATrusteePage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on change link for Are purchaser and vendor connected")
      PurchaserCheckYourAnswers.clickAreCompanyAndVendorConnectedChange()
      Then("User should be navigated to Are purchaser and vendor connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      And("User updates Are purchaser and vendor connected details to No")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.no)
      Then("User clicks on save and continue")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on save and continue")
      PurchaserCheckYourAnswers.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Return Tasklist page")
    }

    Scenario(
      "Complete the Purchaser Questions user journey for additional purchaser for a company and later changing to individual in CYA page",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("incomplete-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserOverviewPage.radioButton(PurchaserOverviewPage.yes)
      And("clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user should be navigated to the Purchaser Before you start page page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      And("clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      Then("the user should be navigated to the confirm page the company name of the purchaser")
      PurchaserConfirmNameOfPurchaserPage.verifyPageTitle(PurchaserConfirmNameOfPurchaserPage.pageTitle)
      And("the user clicks yes")
      PurchaserConfirmNameOfPurchaserPage.radioButton(PurchaserConfirmNameOfPurchaserPage.yes)
      And("clicks Save and Continue")
      PurchaserConfirmNameOfPurchaserPage.saveAndContinue()
      Then("the user should be redirected to address lookup")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitleCompanyStub)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompanyStub)
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompanyStub)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user should be navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitleCompanyStub)
      And("clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("User should be navigated to Do you want to add phone number?")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      And("user selects No on the page")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("user clicks Save and Continue")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitleStub)
      When("the user selects the 'VAT registration number' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.vatRegistrationNumber)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user navigates to VAT Registration number page")
      VATRegistrationNumberPage.verifyPageTitle(VATRegistrationNumberPage.pageTitle)
      And("user enters VAT registration number")
      VATRegistrationNumberPage.input(By.id(VATRegistrationNumberPage.vat), VATRegistrationNumberPage.VATNumber)
      And("user clicks the Continue button")
      VATRegistrationNumberPage.saveAndContinue()
      Then("the user navigates to What type of company page?")
      WhatTypeOfCompany.verifyPageTitle(WhatTypeOfCompany.pageTitle)
      And("user selects 2 types of company")
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Bank, true)
      WhatTypeOfCompany.checkbox(WhatTypeOfCompany.Building_Association, true)
      And("user clicks the Continue button")
      WhatTypeOfCompany.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the Purchaser and Vendor Connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("user is navigated to check your answers page for additional purchaser")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on change link for purchaser type")
      PurchaserCheckYourAnswers.clickPurchaserTypeChange()
      Then("User should be navigated to who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      And("User updates purchaser type to individual")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.individual)
      Then("User clicks on save and continue")
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on missing link for Does purchaser have NI number")
      PurchaserCheckYourAnswers.clickDoPurchaserHaveNINumberChange()
      Then("User should be navigated to does purchaser have NI number page")
      DoesPurchaserHaveNI.verifyPageTitle(DoesPurchaserHaveNI.pageTitle)
      And("User updates yes for NI number")
      DoesPurchaserHaveNI.radioButton(DoesPurchaserHaveNI.yes)
      Then("User clicks on save and continue")
      DoesPurchaserHaveNI.saveAndContinue()
      Then("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      Then("User clicks on missing link for purchaser NI number")
      PurchaserCheckYourAnswers.clickPurchaserNINumberChange()
      Then("User should be navigated to purchaser NI number page")
      PurchaserNationalinsuranceNumberPage.verifyPageTitle(PurchaserNationalinsuranceNumberPage.pageTitle)
      And("User enters NI number")
      PurchaserNationalinsuranceNumberPage.input(By.id(PurchaserNationalinsuranceNumberPage.Nino), "NJ123456C")
      Then("User clicks on save and continue")
      PurchaserNationalinsuranceNumberPage.saveAndContinue()
      And("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on missing link for purchaser date of birth")
      PurchaserCheckYourAnswers.clickPurchaserDOBChange()
      Then("User should be navigated to purchaser date of birth page")
      PurchaserDateOfBirth.verifyPageTitle(PurchaserDateOfBirth.pageTitle)
      And("User enters date of birth")
      PurchaserDateOfBirth.enterDateOfBirth()
      And("the user click Save and Continue")
      PurchaserDateOfBirth.saveAndContinue()
      Then("User should be navigated to purchasers check your answers page")
      PurchaserCheckYourAnswers.verifyPageTitle(PurchaserCheckYourAnswers.pageTitle)
      And("User clicks on save and continue")
      PurchaserCheckYourAnswers.saveAndContinue()
    }

    Scenario(
      "Remove Purchaser Journey with 98 purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("98-purchasers"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      And("The user clicks remove link to remove a purchaser")
      PurchaserOverviewPage.clickRemovePurchaser()
      Then("The user is navigated to Are you sure you want to remove purchaser page")
      RemovePurchaserPage.verifyPageTitle(RemovePurchaserPage.pageTitle)
      And("The user clicks no")
      RemovePurchaserPage.radioButton(RemovePurchaserPage.no)
      When("the user clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("The user is navigated back to Purchaser Overview Page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      And("The user clicks remove link to remove a purchaser")
      PurchaserOverviewPage.clickRemovePurchaser()
      Then("The user is navigated to Are you sure you want to remove purchaser page")
      RemovePurchaserPage.verifyPageTitle(RemovePurchaserPage.pageTitle)
      And("The user clicks yes")
      RemovePurchaserPage.radioButton(RemovePurchaserPage.yes)
      When("the user clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("The user is navigated back to Purchaser Overview Page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Return Tasklist page")
    }
  }
}
