/*
 * Copyright 2025 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.ui.specs

import org.openqa.selenium.By
import org.scalatest.featurespec.AnyFeatureSpec
import org.scalatest.verbs.ShouldVerb
import org.scalatest.{BeforeAndAfterAll, BeforeAndAfterEach, GivenWhenThen}
import uk.gov.hmrc.selenium.webdriver.{Browser, ScreenshotOnFailure}
import uk.gov.hmrc.ui.pages.*
import uk.gov.hmrc.ui.pages.Vendor.*
import uk.gov.hmrc.ui.pages.purchaser.*
import uk.gov.hmrc.ui.util.Users.LoginTypes.HASDIRECT
import uk.gov.hmrc.ui.util.Users.UserTypes.Organisation
import uk.gov.hmrc.ui.tags.*

class PurchaserQuestionsSpec
    extends AnyFeatureSpec
    with BaseSpec
    with GivenWhenThen
    with ShouldVerb
    with BeforeAndAfterAll
    with BeforeAndAfterEach
    with Browser
    with ScreenshotOnFailure {

  Feature("SDLT Filing Frontend Purchaser Questions") {
    Scenario(
      "Complete the Purchaser Questions user journey as an Individual with no purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      /*Then("the user should be navigated to the confirm page when there isn't a full purchaser (no address line 1)")
      PurchaserConfirmNameOfPurchaserPage.verifyPageTitle(PurchaserConfirmNameOfPurchaserPage.pageTitle)
      And("the user clicks yes")
      PurchaserConfirmNameOfPurchaserPage.radioButton(PurchaserConfirmNameOfPurchaserPage.yes)
      PurchaserConfirmNameOfPurchaserPage.saveAndContinue()*/
      Then("the user is navigated to the Who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      When("the user selects the 'An Individual' radio button")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.individual)
      And("clicks the Save and continue button")
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user is navigated to the What is the purchaser’s full name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      When("the user inputs their first name, middle name, and surname")
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.forenameId),
        PurchaserNameOfPurchaserPage.forenameInput
      )
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.middlenameId),
        PurchaserNameOfPurchaserPage.middlenameInput
      )
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.surnameId),
        PurchaserNameOfPurchaserPage.surnameInput
      )
      And("clicks the Save and continue button")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Address lookup page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitle)
      When("the user clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("the user is navigated to the Do you want to add a phone number? page")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      When("the user selects the 'No' radio button")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("clicks the Save and continue button")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Does the Purchaser have a National Insurance number? page")
      DoesPurchaserHaveNI.verifyPageTitle(DoesPurchaserHaveNI.pageTitle)
      When("the user selects the 'Yes' radio button")
      DoesPurchaserHaveNI.radioButton(DoesPurchaserHaveNI.yes)
      And("clicks the Save and continue button")
      DoesPurchaserHaveNI.saveAndContinue()
      Then("the user is navigated to the What is the Purchaser's national insurance number? page")
      PurchaserEnterNINumberPage.verifyPageTitle(PurchaserEnterNINumberPage.pageTitle)
      When("the user inputs a National Insurance Number")
      PurchaserEnterNINumberPage.input(
        By.id(PurchaserEnterNINumberPage.Nino),
        PurchaserEnterNINumberPage.NinoValue
      )
      And("clicks the Save and continue button")
      PurchaserEnterNINumberPage.saveAndContinue()
      Then("the user is navigated to the What is the purchaser Date of Birth? page")
      PurchaserDateOfBirthPage.verifyPageTitle(PurchaserDateOfBirthPage.pageTitle)
      When("the user inputs their Date of Birth")
      PurchaserDateOfBirthPage.enterDateOfBirth()
      And("clicks the Save and continue button")
      PurchaserDateOfBirthPage.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee? page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the purchaser and vendor connected? page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for purchaser name")
      PurchaserCheckYourAnswersPage.clickPurchaserNameChange()
      Then("the user is navigated to the What is the purchaser’s full name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      When("the user updates their name")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.surnameId), "Updated surname")
      And("clicks the Save and continue button")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for National Insurance number")
      PurchaserCheckYourAnswersPage.clickPurchaserNINumberChange()
      Then("the user is navigated to the What is Purchaser's national insurance number? page")
      PurchaserEnterNINumberPage.verifyPageTitle(PurchaserEnterNINumberPage.pageTitle)
      When("the user updates their National Insurance Number")
      PurchaserEnterNINumberPage.input(By.id(PurchaserEnterNINumberPage.Nino), "NJ123456C")
      And("clicks the Save and continue button")
      PurchaserEnterNINumberPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for date of birth")
      PurchaserCheckYourAnswersPage.clickPurchaserDOBChange()
      Then("the user is navigated to the What is the purchaser Date of Birth? page")
      PurchaserDateOfBirthPage.verifyPageTitle(PurchaserDateOfBirthPage.pageTitle)
      When("the user updates their Date of Birth")
      PurchaserDateOfBirthPage.enterDateOfBirth()
      And("clicks the Save and continue button")
      PurchaserDateOfBirthPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks the Save and continue button")
      PurchaserCheckYourAnswersPage.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Return Tasklist page")
    }

    Scenario(
      "Complete the Purchaser Questions user journey as an Individual with no National Insurance Number and no purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      /* Then("the user should be navigated to the confirm page when there isn't a full purchaser (no address line 1)")
      PurchaserConfirmNameOfPurchaserPage.verifyPageTitle(PurchaserConfirmNameOfPurchaserPage.pageTitle)
      And("the user clicks no")
      PurchaserConfirmNameOfPurchaserPage.radioButton(PurchaserConfirmNameOfPurchaserPage.no)
      PurchaserConfirmNameOfPurchaserPage.saveAndContinue()*/
      Then("the user is navigated to the Who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      When("the user selects the 'An Individual' radio button")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.individual)
      And("clicks the Save and continue button")
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user is navigated to the What is the purchaser’s full name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      When("the user inputs their first name, middle name, and surname")
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.forenameId),
        PurchaserNameOfPurchaserPage.forenameInput
      )
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.middlenameId),
        PurchaserNameOfPurchaserPage.middlenameInput
      )
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.surnameId),
        PurchaserNameOfPurchaserPage.surnameInput
      )
      And("clicks the Save and continue button")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Address lookup page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitle)
      When("the user clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("the user is navigated to the Do you want to add phone number? page")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      When("the user selects the 'Yes' radio button")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.yes)
      And("clicks the Save and continue button")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the What is purchaser's phone number page")
      PurchaserEnterPhoneNumberPage.verifyPageTitle(PurchaserEnterPhoneNumberPage.pageTitle)
      When("the user enters their phone number")
      PurchaserEnterPhoneNumberPage.input(
        By.id(PurchaserEnterPhoneNumberPage.phoneNumberInputField),
        PurchaserEnterPhoneNumberPage.phoneNumberValue
      )
      And("clicks the Save and continue button")
      PurchaserEnterPhoneNumberPage.saveAndContinue()
      Then("the user is navigated to the Does the Purchaser have a National Insurance number? page")
      DoesPurchaserHaveNI.verifyPageTitle(DoesPurchaserHaveNI.pageTitle)
      When("the user selects the 'No' radio button")
      DoesPurchaserHaveNI.radioButton(DoesPurchaserHaveNI.no)
      And("clicks the Save and continue button")
      DoesPurchaserHaveNI.saveAndContinue()
      Then("the user is navigated to the Provide a form of ID for purchaser page")
      PurchaserFormOfIDIndividualPage.verifyPageTitle(PurchaserFormOfIDIndividualPage.pageTitle)
      When("the user inputs their ID number or reference")
      PurchaserFormOfIDIndividualPage.input(
        By.id(PurchaserFormOfIDIndividualPage.purchaserIdNumberOrReference),
        PurchaserFormOfIDIndividualPage.idNumberOrReferenceInput
      )
      And("their Country of issue")
      PurchaserFormOfIDIndividualPage.input(
        By.id(PurchaserFormOfIDIndividualPage.purchaserCountryIssued),
        PurchaserFormOfIDIndividualPage.countryIssuedInput
      )
      And("clicks the Save and Continue button")
      PurchaserFormOfIDIndividualPage.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'No' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.no)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the Purchaser and Vendor Connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for purchaser address")
      PurchaserCheckYourAnswersPage.clickPurchaserAddressChange()
      Then("the user is navigated to the Address lookup page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their updated address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      PurchaserAddressPage.enterAddressManually("123", "TEST", "ZZ11 1ZZ")
      Then("the user is navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitle)
      When("the user clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for purchasers phone number")
      PurchaserCheckYourAnswersPage.clickPurchaserPhoneNumberChange()
      Then("the user is navigated to the What is purchaser's phone number page")
      PurchaserEnterPhoneNumberPage.verifyPageTitle(PurchaserEnterPhoneNumberPage.pageTitle)
      When("the user updates their phone number")
      PurchaserEnterPhoneNumberPage.input(
        By.id(PurchaserEnterPhoneNumberPage.phoneNumberInputField),
        PurchaserEnterPhoneNumberPage.phoneNumberValue2
      )
      And("clicks the Save and continue button")
      PurchaserEnterPhoneNumberPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for Purchaser form of id individual")
      PurchaserCheckYourAnswersPage.clickIndivFormOfIDChange()
      Then("the user is navigated to the Provide a Form of ID for purchaser page")
      PurchaserFormOfIDIndividualPage.verifyPageTitle(PurchaserFormOfIDIndividualPage.pageTitle)
      When("the user updates their purchaser ID details")
      PurchaserFormOfIDIndividualPage.input(
        By.id(PurchaserFormOfIDIndividualPage.purchaserIdNumberOrReference),
        PurchaserFormOfIDIndividualPage.idNumberOrReferenceInput2
      )
      And("clicks the Save and continue button")
      PurchaserFormOfIDIndividualPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks the Save and continue button")
      PurchaserCheckYourAnswersPage.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Return Tasklist page")
    }

    Scenario(
      "Complete the Purchaser Questions user journey as an Individual and changed to Company in Check Your Answers with no purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      /*Then("the user should be navigated to the confirm page when there isn't a full purchaser (no address line 1)")
      PurchaserConfirmNameOfPurchaserPage.verifyPageTitle(PurchaserConfirmNameOfPurchaserPage.pageTitle)
      And("the user clicks yes")
      PurchaserConfirmNameOfPurchaserPage.radioButton(PurchaserConfirmNameOfPurchaserPage.yes)
      PurchaserConfirmNameOfPurchaserPage.saveAndContinue()*/
      Then("the user is navigated to the Who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      When("the user selects the 'An Individual' radio button")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.individual)
      And("clicks the Save and continue button")
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user is navigated to the What is the purchaser’s full name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      And("the user inputs their first name, middle name, and surname")
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.forenameId),
        PurchaserNameOfPurchaserPage.forenameInput
      )
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.middlenameId),
        PurchaserNameOfPurchaserPage.middlenameInput
      )
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.surnameId),
        PurchaserNameOfPurchaserPage.surnameInput
      )
      And("clicks the Save and continue button")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Address lookup page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitle)
      When("the user clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("the user is navigated to the Do you want to add phone number? page")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      When("the user selects the 'No' radio button")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("clicks the Save and continue button")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Does the Purchaser have a National Insurance number? page")
      DoesPurchaserHaveNI.verifyPageTitle(DoesPurchaserHaveNI.pageTitle)
      When("the user selects the 'Yes' radio button")
      DoesPurchaserHaveNI.radioButton(DoesPurchaserHaveNI.yes)
      And("clicks the Save and continue button")
      DoesPurchaserHaveNI.saveAndContinue()
      Then("the user is navigated to the What is Purchaser's national insurance number? page")
      PurchaserEnterNINumberPage.verifyPageTitle(PurchaserEnterNINumberPage.pageTitle)
      When("the user inputs a National Insurance Number")
      PurchaserEnterNINumberPage.input(
        By.id(PurchaserEnterNINumberPage.Nino),
        PurchaserEnterNINumberPage.NinoValue
      )
      And("clicks the Save and continue button")
      PurchaserEnterNINumberPage.saveAndContinue()
      Then("the user is navigated to the What is the purchaser Date of Birth? page")
      PurchaserDateOfBirthPage.verifyPageTitle(PurchaserDateOfBirthPage.pageTitle)
      When("the user inputs their Date of Birth")
      PurchaserDateOfBirthPage.enterDateOfBirth()
      And("clicks the Save and continue button")
      PurchaserDateOfBirthPage.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee? page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the purchaser and vendor connected? page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for purchaser type")
      PurchaserCheckYourAnswersPage.clickPurchaserTypeChange()
      Then("the user is navigated to the Who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      When("the user selects the 'A Company' radio button")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.company)
      And("clicks the Save and continue button")
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the link for entering company name")
      PurchaserCheckYourAnswersPage.clickPurchaserNameChange()
      Then("the user is navigated to the What is the company’s name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      When("the user inputs their company name")
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.companyId),
        PurchaserNameOfPurchaserPage.companyName2
      )
      And("clicks the Save and continue button")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the link for entering Form of ID")
      PurchaserCheckYourAnswersPage.clickFormOfIDChange()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitle)
      When("the user selects the 'VAT registration number' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.vatRegistrationNumber)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the link for entering VAT registration number")
      PurchaserCheckYourAnswersPage.clickVATRegistrationNumberChange()
      Then("the user is navigated to the What is the purchaser's VAT Registration number page")
      PurchaserVATRegistrationNumberPage.verifyPageTitle(PurchaserVATRegistrationNumberPage.pageTitle)
      When("the user enters their VAT registration number")
      PurchaserVATRegistrationNumberPage.input(
        By.id(PurchaserVATRegistrationNumberPage.vat),
        PurchaserVATRegistrationNumberPage.VATNumber
      )
      And("clicks the Save and continue button")
      PurchaserVATRegistrationNumberPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the link for Type of company")
      PurchaserCheckYourAnswersPage.clickTypeOfCompanyChange()
      Then("the user is navigated to the What type of company? page")
      PurchaserTypeOfCompanyPage.verifyPageTitle(PurchaserTypeOfCompanyPage.pageTitle)
      When("the user selects 4 types of company")
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Bank, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Building_Association, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Insurance_Assurance_company, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Property_company, true)
      And("clicks the Save and continue button")
      PurchaserTypeOfCompanyPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks the Save and continue button")
      PurchaserCheckYourAnswersPage.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
    }

    Scenario(
      "Complete the Full Purchaser Questions user journey as a Individual with full purchaser with address line 1 stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("full-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserOverviewPage.radioButton(PurchaserOverviewPage.yes)
      And("clicks the Continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Purchaser Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      // User should be navigated to is XXX the surname of the purchaser page
      // User clicks No radio button
      // User clicks Save and Continue
      Then("the user is navigated to the Who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      When("the user selects the 'An Individual' radio button")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.individual)
      And("clicks the Save and continue button")
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user is navigated to the What is the purchaser’s full name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      When("the user inputs their first name, middle name, and surname")
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.forenameId),
        PurchaserNameOfPurchaserPage.forenameInput
      )
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.middlenameId),
        PurchaserNameOfPurchaserPage.middlenameInput
      )
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.surnameId),
        PurchaserNameOfPurchaserPage.surnameInput
      )
      And("clicks the Save and continue button")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Address lookup page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitle)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitle)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user should be navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitle)
      When("the user clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("the user is navigated to is the Purchaser Acting as a Trustee? page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the purchaser and vendor connected? page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
    }

    Scenario(
      "Complete the Purchaser Questions user journey as a Company with VAT ID and no purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      /*Then("the user should be navigated to the confirm page when there isn't a full purchaser (no address line 1)")
      PurchaserConfirmNameOfPurchaserPage.verifyPageTitle(PurchaserConfirmNameOfPurchaserPage.pageTitle)
      And("the user clicks yes")
      PurchaserConfirmNameOfPurchaserPage.radioButton(PurchaserConfirmNameOfPurchaserPage.no)
      PurchaserConfirmNameOfPurchaserPage.saveAndContinue()*/
      Then("the user is navigated to the Who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      When("the user selects the 'A Company' radio button")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.company)
      And("clicks the Save and continue button")
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user is navigated to the What is the company's name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      When("the user inputs their company name")
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.companyId),
        PurchaserNameOfPurchaserPage.companyName2
      )
      And("clicks the Save and continue button")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Address lookup page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitleCompany)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompany)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitleCompany)
      When("the user clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("the user is navigated to the Do you want to add a phone number? page")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      When("the user selects the 'No' radio button")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("clicks the Save and continue button")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitle)
      When("the user selects the 'VAT registration number' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.vatRegistrationNumber)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user is navigated to the What is the purchaser's VAT Registration number page")
      PurchaserVATRegistrationNumberPage.verifyPageTitle(PurchaserVATRegistrationNumberPage.pageTitle)
      When("the user enters their VAT registration number")
      PurchaserVATRegistrationNumberPage.input(
        By.id(PurchaserVATRegistrationNumberPage.vat),
        PurchaserVATRegistrationNumberPage.VATNumber
      )
      And("clicks the Save and continue button")
      PurchaserVATRegistrationNumberPage.saveAndContinue()
      Then("the user is navigated to the What type of company? page")
      PurchaserTypeOfCompanyPage.verifyPageTitle(PurchaserTypeOfCompanyPage.pageTitle)
      When("the user selects 4 types of company")
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Bank, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Building_Association, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Insurance_Assurance_company, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Property_company, true)
      And("clicks the Save and continue button")
      PurchaserTypeOfCompanyPage.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee? page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the purchaser and vendor connected? page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for purchaser name")
      PurchaserCheckYourAnswersPage.clickPurchaserNameChange()
      Then("the user is navigated to the What is the company's name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      When("the user updates their company name")
      PurchaserNameOfPurchaserPage.input(By.id(PurchaserNameOfPurchaserPage.companyId), "Updated Company Name")
      And("clicks the Save and continue button")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for entering VAT registration number")
      PurchaserCheckYourAnswersPage.clickVATRegistrationNumberChange()
      Then("the user is navigated to the What is the purchaser's VAT Registration number page")
      PurchaserVATRegistrationNumberPage.verifyPageTitle(PurchaserVATRegistrationNumberPage.pageTitle)
      When("the user updates their VAT registration number")
      PurchaserVATRegistrationNumberPage.input(
        By.id(PurchaserVATRegistrationNumberPage.vat),
        PurchaserVATRegistrationNumberPage.VATNumber2
      )
      And("clicks the Save and continue button")
      PurchaserVATRegistrationNumberPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks the Save and continue button")
      PurchaserCheckYourAnswersPage.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Add a purchaser button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
    }

    Scenario(
      "Complete the Purchaser Questions user journey as a Company with corporation UTR ID with incomplete purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("incomplete-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      Then("the user is navigated to the Confirm purchaser name page")
      PurchaserConfirmNamePage.verifyPageTitle(PurchaserConfirmNamePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserConfirmNamePage.radioButton(PurchaserConfirmNamePage.yes)
      And("clicks the Continue button")
      PurchaserConfirmNamePage.saveAndContinue()
      Then("the user is navigated to the Address lookup page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitleCompanyStub)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompanyStub)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitleCompanyStub)
      When("the user clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("the user is navigated to the Do you want to add phone number? page")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      When("the user selects the 'No' radio button")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("clicks the Save and continue button")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitleStub)
      When("the user selects the 'Corporation tax Unique Taxpayer Reference (UTR)' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.corporationTaxUTR)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user is navigated to the enter Purchaser's Corporation Tax UTR page")
      PurchaserCorporationTaxUTRPage.verifyPageTitle(PurchaserCorporationTaxUTRPage.pageTitle)
      When("the user inputs their company's Corporation tax Unique Taxpayer Reference (UTR)")
      PurchaserCorporationTaxUTRPage.input(
        By.id(PurchaserCorporationTaxUTRPage.corporationTaxUTR),
        PurchaserCorporationTaxUTRPage.corporationTaxUTRInput
      )
      And("clicks the Save and continue button")
      PurchaserCorporationTaxUTRPage.saveAndContinue()
      Then("the user is navigated to the What type of company? page")
      PurchaserTypeOfCompanyPage.verifyPageTitle(PurchaserTypeOfCompanyPage.pageTitle)
      When("the user selects 3 types of company")
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Public_corporation, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Central_Government, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Other_financial_institute, true)
      And("clicks the Save and continue button")
      PurchaserTypeOfCompanyPage.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee? page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the purchaser and vendor connected? page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for Form of ID")
      PurchaserCheckYourAnswersPage.clickFormOfIDChange()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitleStub)
      When("the user updates to 'Partnership Unique Taxpayer Reference (UTR)' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.partnershipUTR)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user is navigated to the enter Purchaser's Partnership UTR page")
      PurchaserPartnershipUTRPage.verifyPageTitle(PurchaserPartnershipUTRPage.pageTitle)
      When("the user inputs their company's Partnership Unique Taxpayer Reference (UTR)")
      PurchaserPartnershipUTRPage.input(
        By.id(PurchaserPartnershipUTRPage.purchaserUTRReference),
        PurchaserPartnershipUTRPage.purchaserUTRInput
      )
      And("clicks the Save and continue button")
      PurchaserPartnershipUTRPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      And("clicks the Save and continue button")
      PurchaserCheckYourAnswersPage.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the 'Change' link for Purchaser")
      PurchaserOverviewPage.clickPurchaserChange()
    }

    Scenario(
      "Complete the Purchaser Questions user journey as a Company with partnership UTR ID and no purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      Then("the user is navigated to the Who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      When("the user selects the 'A Company' radio button")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.company)
      And("clicks the Save and continue button")
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user is navigated to the What is the company's name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      When("the user inputs their company name")
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.companyId),
        PurchaserNameOfPurchaserPage.companyName2
      )
      And("clicks the Save and continue button")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Address lookup page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitleCompany)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompany)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitleCompany)
      When("the user clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("the user is navigated to the Do you want to add a phone number? page")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      When("the user selects the 'No' radio button")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("clicks the Save and continue button")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitle)
      When("the user selects the 'Partnership Unique Taxpayer Reference (UTR)' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.partnershipUTR)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user is navigated to the enter Purchaser's Partnership UTR page")
      PurchaserPartnershipUTRPage.verifyPageTitle(PurchaserPartnershipUTRPage.pageTitle)
      When("the user inputs their company's Partnership Unique Taxpayer Reference (UTR)")
      PurchaserPartnershipUTRPage.input(
        By.id(PurchaserPartnershipUTRPage.purchaserUTRReference),
        PurchaserPartnershipUTRPage.purchaserUTRInput
      )
      And("clicks the Save and continue button")
      PurchaserPartnershipUTRPage.saveAndContinue()
      Then("the user is navigated to the What type of company? page")
      PurchaserTypeOfCompanyPage.verifyPageTitle(PurchaserTypeOfCompanyPage.pageTitle)
      When("the user selects 3 types of company")
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Local_authority, true)
      PurchaserTypeOfCompanyPage.checkbox(
        PurchaserTypeOfCompanyPage.Unincorporated_sole_trader_other_than_builder,
        true
      )
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Superannuation_or_pension_fund, true)
      And("clicks the Save and continue button")
      PurchaserTypeOfCompanyPage.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee? page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the purchaser and vendor connected? page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for Do you want to add phone number")
      PurchaserCheckYourAnswersPage.clickAddPhoneNumberChange()
      Then("the user is navigated to the Do you want to add phone number? page")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      When("the user selects the 'Yes' radio button")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.yes)
      And("clicks the Save and continue button")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the link for entering a phone number")
      PurchaserCheckYourAnswersPage.clickPurchaserPhoneNumberChange()
      Then("the user is navigated to the What is purchaser's phone number page")
      PurchaserEnterPhoneNumberPage.verifyPageTitle(PurchaserEnterPhoneNumberPage.pageTitle)
      When("the user enters their phone number")
      PurchaserEnterPhoneNumberPage.input(
        By.id(PurchaserEnterPhoneNumberPage.phoneNumberInputField),
        PurchaserEnterPhoneNumberPage.phoneNumberValue
      )
      And("clicks the Save and continue button")
      PurchaserEnterPhoneNumberPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for Type of company")
      PurchaserCheckYourAnswersPage.clickTypeOfCompanyChange()
      Then("the user is navigated to the What type of company? page")
      PurchaserTypeOfCompanyPage.verifyPageTitle(PurchaserTypeOfCompanyPage.pageTitle)
      When("the user updates their types of company")
      PurchaserTypeOfCompanyPage.checkbox(
        PurchaserTypeOfCompanyPage.Unincorporated_sole_trader_other_than_builder,
        false
      )
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Superannuation_or_pension_fund, false)
      And("clicks the Save and continue button")
      PurchaserTypeOfCompanyPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      And("clicks the Save and continue button")
      PurchaserCheckYourAnswersPage.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Add a purchaser button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
    }

    Scenario(
      "Complete the Purchaser Questions user journey as a Company, providing phone number details along with another form of ID with no purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("no-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      Then("the user is navigated to the Who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      When("the user selects the 'A Company' radio button")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.company)
      And("clicks the Save and continue button")
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user is navigated to the What is the company's name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      When("the user inputs their company name")
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.companyId),
        PurchaserNameOfPurchaserPage.companyName2
      )
      And("clicks the Save and continue button")
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Address lookup page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitleCompany)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompany)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user id navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitleCompany)
      When("the user clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("the user is navigated to the Do you want to add a phone number? page")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      When("the user selects the 'Yes' radio button")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.yes)
      And("clicks the Save and continue button")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the What is purchaser's phone number page")
      PurchaserEnterPhoneNumberPage.verifyPageTitle(PurchaserEnterPhoneNumberPage.pageTitle)
      When("the user enters their phone number")
      PurchaserEnterPhoneNumberPage.input(
        By.id(PurchaserEnterPhoneNumberPage.phoneNumberInputField),
        PurchaserEnterPhoneNumberPage.phoneNumberValue
      )
      And("clicks the Save and continue button")
      PurchaserEnterPhoneNumberPage.saveAndContinue()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitle)
      When("the user selects the 'Another form of ID' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.anotherFormOfID)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user is navigated to the Provide a Form of ID Company page")
      PurchaserFormOfIDCompanyPage.verifyPageTitle(PurchaserFormOfIDCompanyPage.pageTitle)
      When("the user inputs their ID number or reference")
      PurchaserFormOfIDCompanyPage.input(
        By.id(PurchaserFormOfIDCompanyPage.idNumberOrReference),
        PurchaserFormOfIDCompanyPage.idNumberOrReferenceInput
      )
      And("their Country of issue")
      PurchaserFormOfIDCompanyPage.input(
        By.id(PurchaserFormOfIDCompanyPage.countryOfIssue),
        PurchaserFormOfIDCompanyPage.countryOfIssueInput
      )
      And("clicks the Save and continue button")
      PurchaserFormOfIDCompanyPage.saveAndContinue()
      Then("the user is navigated to the What type of company? page")
      PurchaserTypeOfCompanyPage.verifyPageTitle(PurchaserTypeOfCompanyPage.pageTitle)
      When("the user selects 3 types of company")
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Unincorporated_builder, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Partnership, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Insurance_Assurance_company, true)
      And("clicks the Save and continue button")
      PurchaserTypeOfCompanyPage.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee? page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the purchaser and vendor connected? page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      And("the user clicks on the 'Change' link for Acting as a Trustee")
      PurchaserCheckYourAnswersPage.clickIsCompanyActingAsTrusteeChange()
      Then("the user is navigated to is the Purchaser Acting as a Trustee? page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'No' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.no)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for Are the purchaser and vendor connected")
      PurchaserCheckYourAnswersPage.clickAreCompanyAndVendorConnectedChange()
      Then("User should be navigated to Are purchaser and vendor connected page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'No' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.no)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      And("clicks the Save and continue button")
      PurchaserCheckYourAnswersPage.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the Add a purchaser button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
    }

    Scenario(
      "Complete the Purchaser Questions user journey for additional purchaser as a company and changing to individual with incomplete purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("incomplete-purchaser"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Before you start page")
      PurchaserBeforeYouStartPage.verifyPageTitle(PurchaserBeforeYouStartPage.pageTitle)
      When("the user clicks the Continue button")
      PurchaserBeforeYouStartPage.saveAndContinue()
      Then("the user is navigated to the Confirm purchaser name page")
      PurchaserConfirmNamePage.verifyPageTitle(PurchaserConfirmNamePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserConfirmNamePage.radioButton(PurchaserConfirmNamePage.yes)
      And("clicks the Continue button")
      PurchaserConfirmNamePage.saveAndContinue()
      Then("the user is navigated to the Address lookup page")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.pageTitleCompanyStub)
      When("the user clicks on the 'Enter the address manually' link")
      PurchaserAddressPage.clickAddressManually()
      And("enters their address manually")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.editPageTitleCompanyStub)
      PurchaserAddressPage.enterAddressManually("123", "ABC", "TE13 1ES")
      Then("the user is navigated to the Property Address page to 'Review and confirm the address'")
      PurchaserAddressPage.verifyPageTitle(PurchaserAddressPage.confirmPageTitleCompanyStub)
      When("the user clicks the Confirm address button")
      PurchaserAddressPage.clickContinueButton()
      Then("the user is navigated to the Do you want to add phone number? page")
      DoesPurchaserHavePhoneNumber.verifyPageTitle(DoesPurchaserHavePhoneNumber.pageTitle)
      When("the user selects the 'No' radio button")
      DoesPurchaserHavePhoneNumber.radioButton(DoesPurchaserHavePhoneNumber.no)
      And("clicks the Save and continue button")
      DoesPurchaserHavePhoneNumber.saveAndContinue()
      Then("the user is navigated to the Confirm Purchaser Identity page")
      PurchaserConfirmPurchaserIdentityPage.verifyPageTitle(PurchaserConfirmPurchaserIdentityPage.pageTitleStub)
      When("the user selects the 'VAT registration number' radio button")
      PurchaserConfirmPurchaserIdentityPage.radioButton(PurchaserConfirmPurchaserIdentityPage.vatRegistrationNumber)
      And("clicks the Save and continue button")
      PurchaserConfirmPurchaserIdentityPage.saveAndContinue()
      Then("the user is navigated to the What is the purchaser's VAT Registration number page")
      PurchaserVATRegistrationNumberPage.verifyPageTitle(PurchaserVATRegistrationNumberPage.pageTitle)
      When("the user enters their VAT registration number")
      PurchaserVATRegistrationNumberPage.input(
        By.id(PurchaserVATRegistrationNumberPage.vat),
        PurchaserVATRegistrationNumberPage.VATNumber
      )
      And("clicks the Save and continue button")
      PurchaserVATRegistrationNumberPage.saveAndContinue()
      Then("the user is navigated to the What type of company? page")
      PurchaserTypeOfCompanyPage.verifyPageTitle(PurchaserTypeOfCompanyPage.pageTitle)
      When("the user selects 2 types of company")
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Bank, true)
      PurchaserTypeOfCompanyPage.checkbox(PurchaserTypeOfCompanyPage.Building_Association, true)
      And("clicks the Save and continue button")
      PurchaserTypeOfCompanyPage.saveAndContinue()
      Then("the user is navigated to is the Purchaser Acting as a Trustee? page")
      PurchaserActingAsATrusteePage.verifyPageTitle(PurchaserActingAsATrusteePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserActingAsATrusteePage.radioButton(PurchaserActingAsATrusteePage.yes)
      And("clicks the Save and continue button")
      PurchaserActingAsATrusteePage.saveAndContinue()
      Then("the user is navigated to the Are the purchaser and vendor connected? page")
      PurchaserAndVendorConnectedPage.verifyPageTitle(PurchaserAndVendorConnectedPage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserAndVendorConnectedPage.radioButton(PurchaserAndVendorConnectedPage.yes)
      And("clicks the Save and continue button")
      PurchaserAndVendorConnectedPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for purchaser type")
      PurchaserCheckYourAnswersPage.clickPurchaserTypeChange()
      Then("the user is navigated to the Who is making the purchase page")
      PurchaserWhoIsMakingThePurchasePage.verifyPageTitle(PurchaserWhoIsMakingThePurchasePage.pageTitle)
      And("the user selects the 'An Individual' radio button")
      PurchaserWhoIsMakingThePurchasePage.radioButton(PurchaserWhoIsMakingThePurchasePage.individual)
      And("clicks the Save and continue button")
      PurchaserWhoIsMakingThePurchasePage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the link for entering the purchaser's full name")
      PurchaserCheckYourAnswersPage.clickPurchaserNameChange()
      Then("the user is navigated to the What is the purchaser’s full name? page")
      PurchaserNameOfPurchaserPage.verifyPageTitle(PurchaserNameOfPurchaserPage.pageTitle)
      When("the user inputs their first name, middle name, and surname")
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.forenameId),
        PurchaserNameOfPurchaserPage.forenameInput
      )
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.middlenameId),
        PurchaserNameOfPurchaserPage.middlenameInput
      )
      PurchaserNameOfPurchaserPage.input(
        By.id(PurchaserNameOfPurchaserPage.surnameId),
        PurchaserNameOfPurchaserPage.surnameInput
      )
      PurchaserNameOfPurchaserPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the 'Change' link for Does the Purchaser have a National Insurance number?")
      PurchaserCheckYourAnswersPage.clickDoPurchaserHaveNINumberChange()
      Then("the user is navigated to the Does the Purchaser have a National Insurance number? page")
      DoesPurchaserHaveNI.verifyPageTitle(DoesPurchaserHaveNI.pageTitle)
      When("the user selects the 'Yes' radio button")
      DoesPurchaserHaveNI.radioButton(DoesPurchaserHaveNI.yes)
      And("clicks the Save and continue button")
      DoesPurchaserHaveNI.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the link for entering National Insurance number")
      PurchaserCheckYourAnswersPage.clickPurchaserNINumberChange()
      Then("the user is navigated to the What is the Purchaser's national insurance number? page")
      PurchaserEnterNINumberPage.verifyPageTitle(PurchaserEnterNINumberPage.pageTitle)
      When("the user inputs a National Insurance Number")
      PurchaserEnterNINumberPage.input(By.id(PurchaserEnterNINumberPage.Nino), PurchaserEnterNINumberPage.NinoValue2)
      And("clicks the Save and continue button")
      PurchaserEnterNINumberPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      When("the user clicks on the link for entering Date of Birth")
      PurchaserCheckYourAnswersPage.clickPurchaserDOBChange()
      Then("User should be navigated to purchaser date of birth page")
      PurchaserDateOfBirthPage.verifyPageTitle(PurchaserDateOfBirthPage.pageTitle)
      When("the user inputs their Date of Birth")
      PurchaserDateOfBirthPage.enterDateOfBirth()
      And("clicks the Save and continue button")
      PurchaserDateOfBirthPage.saveAndContinue()
      Then("the user is navigated to the Check your answers page")
      PurchaserCheckYourAnswersPage.verifyPageTitle(PurchaserCheckYourAnswersPage.pageTitle)
      And("clicks the Save and continue button")
      PurchaserCheckYourAnswersPage.saveAndContinue()
    }

    Scenario(
      "Purchaser Question user journey for removing purchaser with 98 purchaser stub data",
      PurchaserJourney
    ) {
      Given("the user logs in through the Authority Wizard page")
      AuthWizard.login(HASDIRECT, Organisation, returnId = Some("98-purchasers"))
      When("the user clicks on the 'Purchaser Questions' link")
      AboutTheVendorPage.clickLinkById("task-list-link-purchaser-questions")
      Then("the user is navigated to the Purchaser Overview page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("the user clicks the 'Remove' link to remove a purchaser")
      PurchaserOverviewPage.clickRemovePurchaser()
      Then("the user is navigated to Are you sure you want to remove the purchaser page")
      PurchaserRemovePage.verifyPageTitle(PurchaserRemovePage.pageTitle)
      When("the user selects the 'No' radio button")
      PurchaserRemovePage.radioButton(PurchaserRemovePage.no)
      And("clicks the Save and continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview Page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
      When("The user clicks the 'Remove' link to remove a purchaser")
      PurchaserOverviewPage.clickRemovePurchaser()
      Then("the user is navigated to Are you sure you want to remove the purchaser page")
      PurchaserRemovePage.verifyPageTitle(PurchaserRemovePage.pageTitle)
      When("the user selects the 'Yes' radio button")
      PurchaserRemovePage.radioButton(PurchaserRemovePage.yes)
      And("clicks the Save and continue button")
      PurchaserOverviewPage.saveAndContinue()
      Then("the user is navigated to the Purchaser Overview Page")
      PurchaserOverviewPage.verifyPageTitle(PurchaserOverviewPage.pageTitle)
    }
  }
}
